name: deploy-prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_HERMES }}
          username: ${{ secrets.SSH_USER_HERMES }}
          password: ${{ secrets.SSH_PASSWORD_HERMES }}
          script: |
            cd hermes.agence.surf
            sudo git fetch 
            sudo git pull origin dev