name: deploy-testing
on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy Preprod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_TEST_HERMES }}
          username: ${{ secrets.SSH_USER_TEST_HERMES }}
          password: ${{ secrets.SSH_PASSWORD_TEST_HERMES }}
          script: |
            cd /hermes.agence.surf
            sudo git fetch 
            sudo git pull origin testing
